### ISSUE TITLE
Support missing `VAULT_TOKEN` and secrets passed via environment variables

### ISSUE THREAD

**Issue by emk** [faradayio/vault-env-js#1]
`vault-env-js` looks great!

I ran into an issue porting containers to work with our new tools, and thought I would ask you how I should tackle it. Specifically, when doing local development, users may not have a local instance of vault, and they may choose to pass secrets via environment variables. This is currently supported by `credentials`, `credentials-env` and `secret_garden`.

Specifically, we need two things here:

- [ ] If a secret is already present in the environment, that should take precedence over a secret fetched from Vault.
- [ ] If `VAULT_TOKEN` is not available, then only secrets already present in the environment may be used.

This is a blocking issue for several internal tickets. I'm happy to submit a PR if you can sketch out roughly how you'd like this to be implemented. Thank you for any suggestions you can provide!

**Comment by devTristan** [comment]
Hey Eric. As of vault-env-is 4.0.0, environment variables that are already present will not be fetched from vault.

**Comment by emk** [comment]
Confirmed this is working great. Thank you.
